AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  multithreaded statemachine serverless app stack

Resources:
  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: "Multithreaded Download StateMachine"
      Role: arn:aws:iam::aws-account:role/service-role/StepFunctions-aemass-qe-prod-main-workflow-role-87643d68
      DefinitionUri: statemachine/multithread_statemachine.json
      DefinitionSubstitutions: # variables to pass to statemachine
        DivideIntoPartsArn: !GetAtt DivideIntoParts.Arn
        DownloadPartOneArn: !GetAtt DownloadPartOne.Arn
        DownloadPartTwoArn: !GetAtt DownloadPartTwo.Arn
        DownloadPartThreeArn: !GetAtt DownloadPartThree.Arn
        DownloadPartFourArn: !GetAtt DownloadPartFour.Arn
        DownloadPartFiveArn: !GetAtt DownloadPartFive.Arn
        DownloadPartSixArn: !GetAtt DownloadPartSix.Arn
        DownloadPartSevenArn: !GetAtt DownloadPartSeven.Arn
        DownloadPartEightArn: !GetAtt DownloadPartEight.Arn
        DownloadPartNineArn: !GetAtt DownloadPartNine.Arn
        DownloadPartTenArn: !GetAtt DownloadPartTen.Arn
        HttpRequestSizeArn: !GetAtt HttpRequestSize.Arn
        InitStatemachineArn: !GetAtt InitStatemachine.Arn
        IteratorArn: !GetAtt Iterator.Arn
        MergeFileArn: !GetAtt MergeFile.Arn

# Lambda
  DivideIntoParts:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DivideIntoParts
      Role: arn:aws:iam::aws-account:role/aemass-qe-prod-lambda-basic-role
      CodeUri: functions/Divide-into-parts/
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      MemorySize: 10240
      EphemeralStorage:
        Size: 2048
      Timeout: 900
      Architectures:
        - x86_64
      # Layers:
      #   # cloud watch insight
      #   - "arn:aws:lambda:us-east-1:aws-account:layer:pandas-layer:2"
