AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS Multithreaded Download StateMachine

Resources:
  MyTestMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/multithread_statemachine.json
      DefinitionSubstitutions:
        AssignCaseFunctionArn: !GetAtt AssignCaseFunction.Arn
       Policies:
        - "CloudWatchEventsFullAccess"
        - "AWSBatchServiceRole"
        - "AWSBatchFullAccess"
        - "AWSLambdaRole"
        - "CloudWatchFullAccess"
        - "AmazonDynamoDBFullAccess"
        - "CloudWatchLogsFullAccess"
        - "AmazonElasticFileSystemFullAccess"
        - LambdaInvokePolicy:
            FunctionName: !Ref AssignCaseFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref OpenCaseFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref WorkOnCaseFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref CloseCaseFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref EscalateCaseFunction
        - DynamoDBWritePolicy:
            TableName: !Ref TransactionTable

#   AssignCaseFunction:
#     Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
#     Properties:
#       CodeUri: functions/AssignCaseFunction/
#       Handler: app.lambdaHandler
#       Runtime: nodejs16.x
#       Architectures:
#         - x86_64
#   OpenCaseFunction:
#     Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
#     Properties:
#       CodeUri: functions/OpenCaseFunction/
#       Handler: app.lambdaHandler
#       Runtime: nodejs16.x
#       Architectures:
#         - x86_64
#   WorkOnCaseFunction:
#     Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
#     Properties:
#       CodeUri: functions/WorkOnCaseFunction/
#       Handler: app.lambdaHandler
#       Runtime: nodejs16.x
#       Architectures:
#         - x86_64
#   CloseCaseFunction:
#     Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
#     Properties:
#       CodeUri: functions/CloseCaseFunction/
#       Handler: app.lambdaHandler
#       Runtime: nodejs16.x
#       Architectures:
#         - x86_64
#   EscalateCaseFunction:
#     Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
#     Properties:
#       CodeUri: functions/EscalateCaseFunction/
#       Handler: app.lambdaHandler
#       Runtime: nodejs16.x
#       Architectures:
#         - x86_64

# Outputs:
#   # Find out more about other implicit resources you can reference within SAM
#   # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
#   MyTestMachineArn:
#     Description: "MyTestMachine ARN"
#     Value: !Ref MyTestMachine
#   MyTestMachineRole:
#     Description: "IAM Role created for Stock Trading state machine based on the specified SAM Policy Templates"
#     Value: !GetAtt MyTestMachineRole.Arn
